### PR TITLE
Re-org on #19

### PR DESCRIPTION
**Pull request by rachelcarmena**
PR on `is-ide` branch.

Content:

```
.
├── hello-world
│   ├── compiler-plugin
│   │   ├── create-plugin
│   │   └── use-plugin
│   └── idea-plugin
│       ├── compiler-plugin
│       └── ide-plugin
```

It's not possible to use the previous example because the shadowed compiler plugin is not shadowed for IDEA but for including a new plugin.

The new project  is built properly however [this problem with IDEA](https://github.com/arrow-kt/arrow-meta-examples/pull/24#issuecomment-626380124) seems to come from [this issue](https://github.com/johnrengelman/shadow/issues/264).

### CODE REVIEW

**Comment by i-walker** [comment]
Is it possible to build something like this:
```
.
├── hello-world
│   ├── compiler-plugin
│   │   ├── create-plugin
│   │   └── use-plugin
│   └── ide-plugin
```
where `ide-plugin` depends on `compiler-plugin`. If not we could also do something
```
.
├── hello-world
│   ├── compiler-plugin // previously  create-plugin
│   ├── use-plugin
│   └── ide-plugin
``` 
Note: Ide plugins in Meta don't only target IDEA but also other Jetbrains products. But rn we're solely compatible with idea.

**Comment by rachelcarmena** [comment]
> Is it possible to build something like this:
> 
> ```
> .
> ├── hello-world
> │   ├── compiler-plugin
> │   │   ├── create-plugin
> │   │   └── use-plugin
> │   └── ide-plugin
> ```
> 
> where `ide-plugin` depends on `compiler-plugin`. If not we could also do something
> 
> ```
> .
> ├── hello-world
> │   ├── compiler-plugin // previously  create-plugin
> │   ├── use-plugin
> │   └── ide-plugin
> ```
> 
> Note: Ide plugins in Meta don't only target IDEA but also other Jetbrains products. But rn we're solely compatible with idea.

Sorry it's not possible because the Compiler Plugin in the existing example is not shadowed for the IDEA Plugin and it's not necessary for that simple example with the Compiler Plugin. I think it can be interesting to keep different examples.

**Comment by i-walker** [comment]
does the last commit work for you, too @rachelcarmena ?

**Comment by rachelcarmena** [comment]
> does the last commit work for you, too @rachelcarmena ?

I think it's just a rename from `idea-plugin` to `cli-and-ide-plugin`, right? Of course!! Much better :+1: 

I changed `My Ide Plugin` by `Example` because it cannot contains `Plugin` word according to Jetbrains.

It would be necessary to do the same rename in `.github/workflows/build.yml`:

```
cd hello-world/cli-and-ide-plugin
```

instead of:

```
cd hello-world/idea-plugin
``` 

Thanks @i-walker :raised_hands:

**Comment by i-walker** [comment]
Roger will do that

**Review by i-walker — APPROVED** [review]
🎉 Thanks a lot @rachelcarmena. Let's finish the #19, when the plugin is published.

**Comment by rachelcarmena** [comment]
> tada Thanks a lot @rachelcarmena. Let's finish the #19, when the plugin is published.

You're welcome :raised_hands: However, I think it won't be easier when the plugin is published because the plugin includes:

```
lib/compiler-plugin-1.3.61-SNAPSHOT-all.jar
lib/kotlin-stdlib-jdk8-1.3.61.jar
lib/annotations-13.0.jar
lib/kotlin-stdlib-jdk7-1.3.61.jar
lib/kotlin-stdlib-common-1.3.61.jar
lib/kotlin-stdlib-1.3.61.jar
lib/kotlin-html-0.1.4.jar
lib/idea-plugin-1.3.61-SNAPSHOT.jar
```

so it will be necessary to "play" with the dependencies again.

Other plugins do the same as us. A common artifacts repository for SNAPSHOT versions and the Jetbrains Plugin Portal for RELEASE versions. The portal is being used now as a first try to check the process. However, it just will contain RELEASE versions. I think it's interesting to have examples with both SNAPSHOT versions and RELEASE versions.

**Pull request merged**
