### PR TITLE
WIP: Fix IDE example

### PR DESCRIPTION
**Pull request by rachelcarmena**
WIP: waiting for Intellij Gradle Plugin 0.5 to use:

```
   pluginsRepo {
        custom("https://meta.arrow-kt.io/idea-plugin/latest-snapshot/updatePlugins.xml")
        maven('https://plugins.jetbrains.com/maven')
    }
```

because the downloaded Arrow Meta IDE Plugin comes from the pending approval in the marketplace:

```
hello-world/cli-and-ide-plugin/ide-plugin/build/idea-sandbox/plugins/Arrow Meta Intellij IDEA Plugin/lib/
├── annotations-13.0.jar
├── compiler-plugin-1.3.61-SNAPSHOT-all.jar
├── idea-plugin-1.3.61-SNAPSHOT.jar
├── kotlin-stdlib-1.3.61.jar
├── kotlin-stdlib-common-1.3.61.jar
├── kotlin-stdlib-jdk7-1.3.61.jar
└── kotlin-stdlib-jdk8-1.3.61.jar
```

The last name is just `Arrow Meta`.

Another option: https://github.com/arrow-kt/arrow-meta/pull/740/commits/89b17f495b3e179e3cd4bf03d62901f0a013967d

### CODE REVIEW

**Comment by stabbylambda** [comment]
I was playing with this over the weekend and when I saw that IntelliJ Gradle Plugin 0.5.0 was released [this morning](https://github.com/JetBrains/gradle-intellij-plugin/commit/0cd37c3d3b6ec252cfc19c1699d455097da3e994), I bumped this IDE example. I'm not sure if this is the gradle plugin or the arrow meta plugin repository (I suspect it's the latter), but I had to specify the SNAPSHOT timestamp (e.g. `io.arrow-kt.arrow:1.4.10-SNAPSHOT-1601632596`) to get the plugin dependency to resolve:

```
intellij {
    version "$INTELLIJ_IDEA_VERSION"
    pluginName = "Example"
    plugins = ["gradle", "gradle-java", "java", "org.jetbrains.kotlin:${KOTLIN_IDEA_VERSION}", "io.arrow-kt.arrow:1.4.10-SNAPSHOT-1601632596"]
    pluginsRepo {
        custom("https://meta.arrow-kt.io/idea-plugin/latest-snapshot/updatePlugins.xml")
        maven('https://plugins.jetbrains.com/maven')
    }
}
```

**Comment by rachelcarmena** [comment]
Thanks @stabbylambda !! :raised_hands: Happy to know that it really works with the new release. Yes, your code is right and there is a way to avoid the hard-coded version for the SNAPSHOT. I'll update this pull request very soon, thanks again!!!

**Comment by i-walker** [comment]
@rachelcarmena can we close this?

**Comment by rachelcarmena** [comment]
Thanks @i-walker !!! :raised_hands:

**Pull request closed without merging**
